// The one header a ported VCV Rack module needs.
//
//     #include "VcvModule.h"
//     #include "vcv/Fade.cpp"    // upstream, byte-for-byte
//
// That is the whole per-module source file. The module's own registration
// line puts a GMPI plugin in the factory; its config() declarations become
// the plugin XML; its ModuleWidget becomes the patch points and the editor's
// knob layout; and its createPanel() path finds the art the build staged.
//
// ORDER MATTERS: this header must come BEFORE the module's .cpp, because
// that .cpp is what instantiates createModel() and so needs the registration
// machinery already declared.
//
// Knobs, all optional and all set once per plugin (CMake is the natural
// place), never per module:
//
//     VCV_MODULE_ID_PREFIX   plugin id is prefix + slug, default "VCV: "
//     VCV_MODULE_CATEGORY    default "VCV"
//     VCV_MODULE_VENDOR      default "VCV (ported)"
//     VCVADAPTOR_NO_GUI      DSP only; skips the editor and its gmpi_ui and
//                            tinyxml2 dependencies
//     VCV_NO_AUTO_REGISTER   per translation unit: register by hand with
//                            vcv::registerModule() instead

#pragma once

// Plugin-wide metadata, generated by the build. It has to arrive before
// VcvAutoRegister.h applies its own defaults. A generated header rather than
// -D defines because these values contain spaces and parentheses, which do
// not survive MSBuild's PreprocessorDefinitions list intact.
#ifdef VCV_PLUGIN_CONFIG_HEADER
	#include VCV_PLUGIN_CONFIG_HEADER
#endif

// THIRD-PARTY HEADERS FIRST, and this is not stylistic.
//
// plugin.hpp ends with `using namespace rack;` — exactly as Rack's own does,
// which is why Fundamental's sources can say Module and Vec unqualified. The
// cost is that rack::Rect and rack::Vec then sit in the global namespace, and
// gmpi_ui has its own Rect and Vec. Include SvgParser.h afterwards and every
// `Rect` inside it becomes ambiguous.
//
// So the GMPI and gmpi_ui headers are pulled in here, before anything drags
// in the mock. Each of the adaptor headers already orders its own includes
// correctly; this covers the case where they are combined.
#include "Processor.h"

#ifndef VCVADAPTOR_NO_GUI
	#include "helpers/GmpiPluginEditor.h"
	#include "helpers/SvgParser.h"
#endif

#include "VcvAdaptor.h"

#ifndef VCVADAPTOR_NO_GUI
	#include "VcvEditor.h"
#endif

#include "VcvAutoRegister.h"

// Panel art, staged by the build. The consuming CMake generates a header
// registering every res/*.svg and passes its name here, so the editor can
// resolve the path a module names in createPanel() without anyone repeating
// it. Absent, panels must be passed to createEditor() explicitly.
#ifdef VCV_PANEL_RESOURCES_HEADER
	#include VCV_PANEL_RESOURCES_HEADER
#endif
